### ISSUE TITLE
seg fault on register

### ISSUE THREAD

**Issue by kubsnn** [mchlebosz/IPC-Chat-Service#33]
for some reason client throws segfault after connecting to server queue in register process but not in login (?)

**Comment by mchlebosz** [comment]
How to replicate problem?

**Comment by mchlebosz** [comment]
I've registered several users and logged in on them and not found the problem yet. Previous problem, where when registering already existing user, segfault occured was already fixed in Hotfix in dev branch

**Comment by mchlebosz** [comment]
![329140525_1253935102146035_766117079514594020_n](https://user-images.githubusercontent.com/33816049/220693904-938af27c-fd2d-4a80-9034-a28693e5f113.png)
![image](https://user-images.githubusercontent.com/33816049/220693744-c496f269-49da-4410-9b0a-32e7d55e0f2b.png)

**Comment by mchlebosz** [comment]
Could you describe the problem more precisely and provide replication instructions?

**Comment by kubsnn** [comment]
Problem fixed.
